name: Metrics
on:
  # Se actualiza cada 24 horas automáticamente
  schedule: [{cron: "0 0 * * *"}]
  # Permite que lo ejecutes manualmente si quieres ver cambios ya
  workflow_dispatch:
  # Se ejecuta cada vez que haces un cambio en el main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Tu token secreto
          token: ${{ secrets.METRICS_TOKEN }}

          # Opciones básicas
          user: eli03pz
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Guayaquil

          # CONFIGURACIÓN DE TU ESTILO
          config_display: large
          
          # Esto fuerza el modo oscuro y usa tu color rosa
          plugin_lines: yes
          plugin_lines_color: "#f75c7e"
          plugin_traffic: yes
          
          # Color del borde y textos (Personalización avanzada)
          # Esto intenta imitar el estilo neon/dark
          config_style: |
             .header { color: #f75c7e; }
             .stat { color: #ffffff; }