name: Metrics
on:
  # Se actualiza cada 24 horas
  schedule: [{cron: "0 0 * * *"}]
  # Permite ejecutarlo manualmente
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Tu archivo se llamará github-metrics.svg
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Configuración Básica
          user: eli03pz
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Guayaquil
          
          # --- DISEÑO Y COLOR ROSA ---
          config_display: large
          plugin_lines: yes
          plugin_lines_color: "#f75c7e"
          plugin_traffic: yes
          config_style: |
             .header { color: #f75c7e; }
             .stat { color: #ffffff; }
             .achievement-title { fill: #f75c7e !important; }

          # --- AQUÍ ESTÁN LOS ACHIEVEMENTS ---
          plugin_achievements: yes
          plugin_achievements_display: detailed # Muestra los detalles, no solo iconos
          plugin_achievements_secrets: yes      # Muestra logros secretos si los tienes
          plugin_achievements_threshold: C      # Muestra desde rango C hacia arriba